import type { Product } from '@server/features/products/types';
export const seedProducts: Product[] = [
 {id:'essential-tee',name:'Áo thun Essential Cotton',category:'Áo thun',gender:'Unisex',price:249000,original_price:299000,image:'/images/tee.jpg',material:'Cotton 100%',colors:['Trắng','Đen','Xám'],sizes:['S','M','L','XL'],is_new:1,active:1,description:'Một chiếc áo dễ mặc mỗi ngày. Cotton mềm thoáng, phom relaxed vừa vặn và đường may gọn gàng.'},
 {id:'oxford-shirt',name:'Sơ mi Oxford Relaxed',category:'Áo sơ mi',gender:'Nam',price:459000,original_price:0,image:'/images/shirt.jpg',material:'Cotton Oxford',colors:['Trắng','Xám'],sizes:['S','M','L','XL'],is_new:1,active:1,description:'Sơ mi Oxford với phom thoải mái. Mặc riêng hoặc khoác ngoài áo thun để hoàn thiện một bộ đồ nhẹ nhàng.'},
 {id:'straight-jeans',name:'Quần jeans Straight Fit',category:'Quần',gender:'Unisex',price:599000,original_price:699000,image:'/images/jeans.jpg',material:'Denim cotton',colors:['Xanh denim','Đen'],sizes:['S','M','L','XL'],is_new:0,active:1,description:'Quần jeans ống đứng, cạp vừa. Thiết kế tối giản dễ phối cùng sơ mi, áo thun và áo len.'},
 {id:'soft-knit',name:'Áo len Soft Knit',category:'Áo len',gender:'Nữ',price:489000,original_price:0,image:'/images/knit.jpg',material:'Cotton pha sợi dệt kim',colors:['Kem','Xám'],sizes:['S','M','L'],is_new:1,active:1,description:'Áo len dệt kim mềm mại, cổ tròn và phom thả nhẹ. Một lựa chọn thoải mái cho những ngày trời dịu mát.'},
 {id:'city-blazer',name:'Blazer City Tailored',category:'Áo khoác',gender:'Nữ',price:899000,original_price:1099000,image:'/images/blazer.jpg',material:'Vải suiting có lót',colors:['Đen','Kem'],sizes:['S','M','L'],is_new:1,active:1,description:'Blazer phom suông, vai vừa và hàng khuy tinh tế. Phối cùng quần jeans cho ngày thường hoặc quần âu khi đi làm.'},
 {id:'everyday-trousers',name:'Quần suông Everyday',category:'Quần',gender:'Nữ',price:549000,original_price:0,image:'/images/pants.jpg',material:'Polyester pha viscose',colors:['Kem','Đen'],sizes:['S','M','L','XL'],is_new:0,active:1,description:'Quần suông cạp cao, bề mặt vải mịn và ít nhăn. Thiết kế vừa đủ chỉn chu cho công việc và những buổi hẹn.'},
 {id:'weekend-dress',name:'Đầm Weekend Midi',category:'Váy & đầm',gender:'Nữ',price:649000,original_price:799000,image:'/images/dress.jpg',material:'Cotton pha viscose',colors:['Trắng','Kem'],sizes:['S','M','L'],is_new:0,active:1,description:'Đầm midi dáng nhẹ, đường cắt thanh lịch. Dễ kết hợp cùng túi và sandal cho cuối tuần.'},
 {id:'everyday-bag',name:'Túi Everyday Shoulder',category:'Phụ kiện',gender:'Nữ',price:389000,original_price:0,image:'/images/bag.jpg',material:'Da tổng hợp',colors:['Nâu','Đen'],sizes:['Freesize'],is_new:0,active:1,description:'Túi đeo vai gọn nhẹ, đủ chỗ cho những món đồ cần thiết. Thiết kế tối giản đồng hành cùng mọi bộ trang phục.'}
];
